#!/bin/bash
#
# Make sure sense data is correct, most notable that the additional
# sense length field is set.
#
# Based on a testcase from Roland Dreier <roland@purestorage.com>.
#

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_require_command sg_raw

sg_raw -v /dev/sda 2 0 0 0 0 0

# success, all done
echo "*** done"
rm -f $seq.full
status=0
