#!/bin/bash
#
# Check the sense key for INVALID FIELD IN {PARAMETER LIST,CDB}
#
# According to SPC-4, the sense key for commands that are failed with
# INVALID FIELD IN PARAMETER LIST and INVALID FIELD IN CDB should be
# ILLEGAL REQUEST (5h)
#
# Based on a test case from Roland Dreier <roland@purestorage.com>.
#

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_require_command sg_raw

sg_raw -r 255 -v $TEST_DEV 3 1 0 0 ff 0

# success, all done
echo "*** done"
rm -f $seq.full
status=0
