#!/bin/bash
#
# Test that INQUIRY with the EVPD flag for an incorrect EVPD page fails.
#
# Based on a bug report from Roland Dreier / Pure Storage, Inc.
#

seq=`basename $0`
echo "QA output created by $seq"

here=`pwd`
tmp=/tmp/$$
status=1	# failure is the default!

# get standard environment, filters and checks
. ./common.rc
. ./common.filter

_require_command sg_raw

execute_cdb -r 54 0x12 1 0xbf 0 36 0

# success, all done
echo "*** done"
rm -f $seq.full
status=0
